[package]
distribution = "2201.12.0"
org = "xlibb"
name = "pdfbox"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["pdfbox"]
icon = "icon.png"
repository = "https://github.com/xlibb/module-pdfbox"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.xlibb.pdfbox"
artifactId = "pdfbox-native"
version = "@toml.version@"
path = "../native/build/libs/pdfbox-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "@pdfbox.version@"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "fontbox"
version = "@pdfbox.version@"
