[package]
distribution = "2201.12.0"
org = "xlibb"
name = "pdfbox"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["pdfbox"]
icon = "icon.png"
repository = "https://github.com/xlibb/module-pdfbox"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.xlibb.pdfbox"
artifactId = "pdfbox-native"
version = "2.0.0"
path = "../native/build/libs/pdfbox-native-2.0.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "2.0.32"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "fontbox"
version = "2.0.32"
